Clipboard


Create a vector of the file names for spam and ham using the base function ```dir```.
```{r}
ham_names<-dir("~/Documents/GitHub/DATA607_Proj4/data/easy_ham")
spam_names<-dir("~/Documents/GitHub/DATA607_Proj4/data/spam")
```

Create a vector containing the contents of each message.
```{r}
#Create an empty vector
ham_message <- c()

#Use a for loop to paste each message into the list
for(i in 1:length(spam_source)) {
  connection <- file(spam_source[i], open="rt", encoding="latin1")
  text <- readLines(connection)
  msg <- text[seq(which(text=="")[1]+1,length(text),1)]
  close(connection)
  vector<-c(i,paste(msg, collapse=" "))
  ham_message<-rbind(ham_message,vector)
}

#Inspect results
head(ham_message)



```


```{r}
  connection <- file(spam_source[[1]])
  tmp <- readLines(connection)
  close.connection(connection)
  msg <- str_c(tmp, collapse = "")
  corpus_name <- Corpus(VectorSource(msg))
```

```{r}
test <- c("a short sentence.", "A slightly longer sentence.", "A much longer sentence that includes more words.")
corpus <- Corpus(VectorSource(test))
corpus <- tm_map(corpus, removePunctuation)
corpus
```

